#!/usr/bin/env bash

set -euxo pipefail

helm upgrade --install --namespace kube-system --create-namespace monodots-bootstrap kubernetes-bootstrap

# Apply CRDs first
kubectl get crd alertmanagerconfigs.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl get crd alertmanagers.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
kubectl get crd podmonitors.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
kubectl get crd probes.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
kubectl get crd prometheusagents.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
kubectl get crd prometheuses.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
kubectl get crd prometheusrules.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
kubectl get crd scrapeconfigs.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
kubectl get crd servicemonitors.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
kubectl get crd thanosrulers.monitoring.coreos.com >/dev/null 2>&1 || kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.82.0/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml

helm upgrade --install --namespace kube-system --create-namespace monodots-crd kubernetes-crd

helm upgrade --install --skip-crds --namespace kube-system --create-namespace monodots-system kubernetes-system
helm upgrade --install --skip-crds --create-namespace monodots kubernetes