#!/usr/bin/env bash

helm upgrade --install --namespace kube-system --create-namespace monodots-bootstrap kubernetes-bootstrap
helm upgrade --install --namespace kube-system --create-namespace monodots-crd kubernetes-crd
helm upgrade --install --namespace kube-system --create-namespace monodots-system kubernetes-system
helm upgrade --install --create-namespace monodots kubernetes