apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-searxng
spec:
  rules:
  - host: search.lsferreira.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monodots-searxng
            port:
              number: 8080
  ingressClassName: nginx