apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-searxng-to-redis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: searxng-redis
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: searxng
    ports:
    - protocol: TCP
      port: 6379
  policyTypes:
  - Ingress
