apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-searxng-redis-only-from-client
spec:
  podSelector:
    matchLabels:
      role: searxng-redis-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: searxng-redis-client
      ports:
        - protocol: TCP
          port: 6379