secrets-store-csi-driver:
  tokenRequests:
    - audience: infisical
  enableSecretRotation: true
  rotationPollInterval: 2m
  syncSecret:
    enabled: true

metrics-server:
  rbac:
    create: true
    pspEnabled: true

  args:
    - --kubelet-insecure-tls

  apiService:
    create: true
    # Turn to false when https://github.com/kubernetes-sigs/metrics-server/issues/1664 is resolved
    insecureSkipTLSVerify: true

  tls:
    type: "cert-manager"
    certManager:
      addInjectorAnnotations: true
    helm:
      lookup: false
    existingSecret:
      lookup: false

ingress-nginx:
  namespaceOverride: "kube-system"

  service:
    enabled: true
    type: ClusterIP
    httpPort: 80
    httpsPort: 443

    externalTrafficPolicy: Local

  controller:
    kind: DaemonSet

    ingressClassResource:
      enabled: true
      default: true

    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443