secrets-store-csi-driver:
  tokenRequests:
    - audience: infisical
  enableSecretRotation: true
  rotationPollInterval: 2m
  syncSecret:
    enabled: true

ingress-anubis:
  replicaCount: 5
  config:
    WRAPPED_INGRESS_CLASS_NAME: "traefik"
  podAnnotations:
    descheduler.alpha.kubernetes.io/evict: "false"
  nodeSelector:
    node-role.kubernetes.io/gateway: "true"

descheduler:
  deschedulerPolicy:
    profiles:
      - name: default
        pluginConfig:
          - name: DefaultEvictor
            args:
              # FIXME: use PodDisruptionBudget
              minReplicas: 2

              podProtections:
                extraEnabled:
                - "PodsWithoutPDB"

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      replicas: 3
  crds:
    enabled: true
    upgradeJob:
      enabled: true