secrets-store-csi-driver:
  tokenRequests:
    - audience: infisical
  enableSecretRotation: true
  rotationPollInterval: 2m
  syncSecret:
    enabled: true

metrics-server:
  rbac:
    create: true
    pspEnabled: true

  args:
    - --kubelet-insecure-tls

  apiService:
    create: true
    # Turn to false when https://github.com/kubernetes-sigs/metrics-server/issues/1664 is resolved
    insecureSkipTLSVerify: true

  tls:
    type: "cert-manager"
    certManager:
      addInjectorAnnotations: true
    helm:
      lookup: false
    existingSecret:
      lookup: false

ingress-nginx:
  namespaceOverride: "kube-system"

  service:
    enabled: true
    type: ClusterIP
    httpPort: 80
    httpsPort: 443

    externalTrafficPolicy: Local

  controller:
    config:
      use-gzip: true
      enable-brotli: true

      enable-real-ip: true
      proxy-real-ip-cidr: |
        173.245.48.0/20,
        103.21.244.0/22,
        103.22.200.0/22,
        103.31.4.0/22,
        141.101.64.0/18,
        108.162.192.0/18,
        190.93.240.0/20,
        188.114.96.0/20,
        197.234.240.0/22,
        198.41.128.0/17,
        162.158.0.0/15,
        104.16.0.0/13,
        104.24.0.0/14,
        172.64.0.0/13,
        131.0.72.0/22

    kind: DaemonSet

    ingressClassResource:
      enabled: true
      default: true

    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443