secrets-store-csi-driver:
  tokenRequests:
    - audience: infisical
  enableSecretRotation: true
  rotationPollInterval: 2m
  syncSecret:
    enabled: true

ingress-anubis:
  config:
    WRAPPED_INGRESS_CLASS_NAME: "traefik"