secrets-store-csi-driver:
  tokenRequests:
    - audience: infisical
  enableSecretRotation: true
  rotationPollInterval: 2m
  syncSecret:
    enabled: true

ingress-anubis:
  replicaCount: 5
  config:
    WRAPPED_INGRESS_CLASS_NAME: "traefik"
  nodeSelector:
    node-role.kubernetes.io/gateway: "true"

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      replicas: 3
  crds:
    enabled: true
    upgradeJob:
      enabled: true