apiVersion: v2
name: monodots
description: A Helm chart for Kubernetes

dependencies:
  # - name: traefik
  #   repository: https://traefik.github.io/charts
  #   version: 34.4.1
  #   alias: traefik-ingress
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 22.0.6
    alias: searxng-redis
  - name: searxng
    repository: https://raw.githubusercontent.com/searxng/searxng-helm-chart/refs/heads/gh-pages
    version: 1.0.1
  - name: wireguard
    repository: https://bryopsida.github.io/wireguard-chart
    version: 0.29.0
  - name: emqx-enterprise
    repository: https://repos.emqx.io/charts
    version: 5.10.0
  - name: rss-bridge
    repository: oci://tccr.io/truecharts
    version: 13.1.0
  - name: codeproject-ai-server
    repository: oci://tccr.io/truecharts
    version: 4.5.1

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

maintainers:
- email: k8s@lsferreira.net
  name: Luis Ferreira