# traefik-ingress:
#   service:
#     enabled: true
#     type: ClusterIP

#   deployment:
#     enabled: true
#     replicas: 3

#   ingressRoute:
#     dashboard:
#       enabled: true

#   ports:
#     traefik:
#       port: 8888
#     web:
#       port: 8080

#       redirections:
#         entryPoint:
#           to: websecure
#           scheme: https
#           permanent: true

#     websecure:
#       port: 8443

#       tls:
#         enabled: true

#       http3:
#         enabled: true

wireguard:
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
  daemonSet: true
  useHostPort: true
  secretName: monodots-wg-privkey
  wireguard:
    allowWan: false
    clients:
    - AllowedIPs: "10.34.0.2/32"
      PublicKey: "IDv2UdXfzLjOeW/JL7jV373Cr0gyVYdF4mjo4vo4bX0="
    serverAddress: "10.34.0.1/24"
    serverCidr: "10.34.0.0/24"

searxng-redis:
  fullnameOverride: searxng-redis
  architecture: standalone
  auth:
    enabled: false
  
  # no need to for persistence for cache nodes
  master:
    persistence:
      enabled: false

searxng:
  controller:
    # TODO: increase number of replicas when more nodes are available
    replicas: 3

    dnsPolicy: None
    dnsConfig:
      nameservers:
        - 8.8.8.8
        - 1.1.1.1
      searches:
        - cluster.local

  persistence:
    limiter:
      enabled: true
      type: configMap
      name: configmap-searxng-limiter
      mountPath: /etc/searxng/limiter.toml
      subPath: limiter.toml

  searxng:
    config:
      use_default_settings: true

      ui:
        static_use_hash: true
        query_in_title: true
        infinite_scroll: true

        theme_args:
          simple_style: dark

      server:
        image_proxy: true
        limiter: true
        method: "GET"

        http_protocol_version: "1.1"
      
      redis:
        url: redis://@searxng-redis-master:6379/0

      general:
        debug: false

      preferences:
        lock:
          - autocomplete
          - favicon
          - doi_resolver

      outgoing:
        request_timeout: 5.0
        max_request_timeout: 15.0

        pool_connections: 512
        pool_maxsize: 32

      search:
        autocomplete: "google"
        favicon_resolver: "duckduckgo"
        default_lang: "all"

        formats:
          - html
          # - json
          # - csv
          # - rss
      
      plugins:
        searx.plugins.calculator.SXNGPlugin:
          active: true

        searx.plugins.hash_plugin.SXNGPlugin:
          active: true

        searx.plugins.self_info.SXNGPlugin:
          active: true

        searx.plugins.unit_converter.SXNGPlugin:
          active: true

        searx.plugins.ahmia_filter.SXNGPlugin:
          active: true

        searx.plugins.hostnames.SXNGPlugin:
          active: true

        searx.plugins.time_zone.SXNGPlugin:
          active: true

        searx.plugins.oa_doi_rewrite.SXNGPlugin:
          active: true

        searx.plugins.tor_check.SXNGPlugin:
          active: true

        searx.plugins.tracker_url_remover.SXNGPlugin:
          active: true

  env:
    BASE_URL: "https://search.lsferreira.net/"
    AUTOCOMPLETE: "true"
    TZ: "Europe/Lisbon"
    GENERATION: "46e7910e-df77-431f-a481-535f84b569f2"

    # TODO: increase workers/threads when more nodes are available
    UWSGI_WORKERS: 2
    UWSGI_THREADS: 2

rss-bridge:
  service:
    main:
      ports:
        main:
          port: 10225

codeproject-ai-server:
  service:
    main:
      ports:
        main:
          port: 32168
          targetPort: 32168