traefik-ingress:
  service:
    enabled: true
    type: ClusterIP

  deployment:
    enabled: true
    replicas: 3

  ingressRoute:
    dashboard:
      enabled: true

  ports:
    traefik:
      port: 8888
    web:
      port: 8080

      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

    websecure:
      port: 8443

      tls:
        enabled: true

      http3:
        enabled: true

searxng:
  redis:
    enabled: true

  controller:
    replicas: 3

  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
    searches:
      - cluster.local

  searxng:
    config:
      use_default_settings: true

      server:
        image_proxy: true

      general:
        debug: false

      search:
        autocomplete: 'duckduckgo'
  env:
    BASE_URL: "http://search.lsferreira.net/"