wireguard:
  daemonSet: true

  autoscaling:
    minReplicas: 1
    maxReplicas: 2

  useHostPort: true
  hostPort: 51822
  service:
    type: ClusterIP
    port: 51822
    ipFamilyPolicy: PreferDualStack

  nodeSelector:
    node-role.kubernetes.io/gateway: "true"

  # secretName: monodots-wg-privkey
  wireguard:
    clients:
    - AllowedIPs: "10.34.0.2/32"
      PublicKey: "rrNHUE1vmRIi1JP5DR8A792jsqtv+vJbGoqZuxX6gHE="
      PersistentKeepalive: 25
    serverAddress: "10.34.0.1/24"
    serverCidr: "10.34.0.0/24"
    forwardIPv6: true

rss-bridge:
  global:
    nameOverride: rss-bridge
  controllers:
    main:
      replicas: 5
      type: deployment
      strategy: RollingUpdate
      rollingUpdate:
        unavailable: 1
      containers:
        main:
          image:
            repository: ghcr.io/rss-bridge/rss-bridge
            tag: latest
            pullPolicy: Always

          env: {}
  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 80

rss-bridge-staging:
  global:
    nameOverride: rss-bridge
  controllers:
    main:
      replicas: 1
      type: deployment
      strategy: RollingUpdate
      rollingUpdate:
        unavailable: 1
      containers:
        main:
          image:
            repository: ghcr.io/rss-bridge/rss-bridge
            tag: latest
            pullPolicy: Always

          env: {}
  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 80